FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CsvParser/CsvParser.fsproj", "CsvParser/"]
RUN dotnet restore "CsvParser/CsvParser.fsproj"
COPY . .
WORKDIR "/src/CsvParser"
RUN dotnet build "CsvParser.fsproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CsvParser.fsproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CsvParser.dll"]
